Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\programdata\anaconda3\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Training
X_train, y_train =load_images('train')
X_test, y_test = load_images('test')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-3-6d9ebc807d02>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Training[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mX_train[0m[1;33m,[0m [0my_train[0m [1;33m=[0m[0mload_images[0m[1;33m([0m[1;34m'train'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mX_test[0m[1;33m,[0m [0my_test[0m [1;33m=[0m [0mload_images[0m[1;33m([0m[1;34m'test'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-2-66e52f0f6048>[0m in [0;36mload_images[1;34m(root_dir_name)[0m
[0;32m     10[0m         [0msub_dir_path[0m[1;33m=[0m[0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mjoin[0m[1;33m([0m[0mmain_dir[0m[1;33m,[0m [0mroot_dir_name[0m[1;33m,[0m [0msub_dir_name[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m [1;33m[0m[0m
[1;32m---> 12[1;33m         [1;32mfor[0m [0mimage_name[0m [1;32min[0m [0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0msub_dir_path[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     13[0m             [1;32mif[0m [0mlabel[0m[1;33m==[0m[1;36m1[0m [1;32mand[0m [1;34m'virus'[0m [1;32min[0m [0mimage_name[0m[1;33m:[0m [1;32mcontinue[0m[1;33m[0m[1;33m[0m[0m
[0;32m     14[0m             [0mimage_path[0m[1;33m=[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mjoin[0m[1;33m([0m[0msub_dir_path[0m[1;33m,[0m [0mimage_name[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [WinError 3] 系統找不到指定的路徑。: './chest_xray/chest_xray/train\\NORMAL'
FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: './chest_xray/chest_xray/train\\NORMAL'

